### PR TITLE
dev summit demo check in

### PR DESCRIPTION
**Pull request by rchintapalli**
@doneill Please review this check in

### CODE REVIEW

**Comment by doneill** [comment]
@rchintapalli Please include a README at the root of the **LocalGeofence** folder.  Include developer instructions.  You can also add a README in the **app** folder explaining how to use the demo.  Also you need to include your gitignore files as well.  Once you have that I can review the code.

**Comment by rchintapalli** [comment]
@doneill included ReadMe file at root which explains how to use the app. Also inlcuded the gitignore files

**Comment by rchintapalli** [comment]
@doneill made the changes

**Comment by doneill** [comment]
@rchintapalli I am unable to get this project into Android Studio.  I have added a gradle wrapper and a root build file but Android Studio is not recognizing the project as an Android project.  I can continue to investigate the issue.  Furthermore I am not able to download the required data, first it asks me to log in (which it shouldn't) and then doesn't allow me to access the data after I login.  Can you ensure the data is available to everyone w/o requiring a login?

**Comment by doneill** [comment]
@rchintapalli Merging

**Pull request merged**
