### PR TITLE
Shell0002/2015 eds

### PR DESCRIPTION
**Pull request by shellygill**
@doneill - a PR for some demo code written for Berlin developer summit - can  you review when you have a minute? 
- Device Location - uses 10.2.7, and also I have updated to target SDK 23, and added marshmallow permissions requesting pattern.
- Jump Zoom - uses a Quartz post-beta 1 daily. This is the one I mentioned to you recently - targeting Beta 2 but can be used for information just to show the APIs, until beta 2 is released.

### CODE REVIEW

**Comment by doneill** [comment]
@shellygill Some initial comments on the DeviceLocation demo.  

Can you add README.md files to root of the apps and remove the README.md at the root of the app project folders?  Add license info, screenshots, etc. to better contextualize the demos. 

I could not find the commit to comment, but can you remove unnecessary `return` in last statement of `void` method on line 110?

**Comment by doneill** [comment]
@shellygill Long time, I did make some comments if you want to address and get this merged.

**Comment by shellygill** [comment]
@doneill - I'm afraid it never made it back to the top of my todo stack... I'll get back to it.

**Comment by doneill** [comment]
@shellygill No worries, will be good to get in the repo when you have time again :-)

**Comment by doneill** [comment]
@shellygill Trying to clean up PR's, some minor comments to address then we can merge.

**Comment by doneill** [comment]
@shellygill I updated the app with the comments I provided and tested.  I made a basic README that I think you should circle back and update when you have a chance.  Nice Demo!

**Pull request merged**
