### PR TITLE
Dop/java routing demo

### PR DESCRIPTION
**Pull request by doneill**
Java Routing Demo

### CODE REVIEW

**Comment by doneill** [comment]
@mbcoder  Please review.

**Comment by mbcoder** [comment]
@doneill this is fine.  I made a change to the comments in the application and have applied this to your branch.

**Comment by doneill** [comment]
Thanks @mbcoder I have left the details on how to work with this demo until we release Beta-2 as some workflows are subject to change.  Merging now.

**Comment by doneill** [comment]
Created #27 to follow up with the README.

**Pull request merged**
